### ISSUE TITLE
Application Icons

### ISSUE THREAD

**Issue by evan-buss** [evan-buss/Yin-Yang#1]
The application needs icons that match the elementary OS icon style guidelines.

I was thinking that the internet browser icon can be adapted since it is basically the Yin-Yang symbol.

![image](https://user-images.githubusercontent.com/18509589/58900245-cc447680-86cc-11e9-80d8-73f5e7d8f0cd.png)

We also need two wingpanel "symbolic" versions of the icon. One should denote light mode and one should denote dark mode. The symbolic icons are typically black and white. Here are some current examples.

![image](https://user-images.githubusercontent.com/18509589/58900351-06ae1380-86cd-11e9-9acc-8bcddadf45ce.png)

![image](https://user-images.githubusercontent.com/18509589/58900443-2e04e080-86cd-11e9-9381-eac82ed88dd6.png)

Any designs or help would be appreciated!

**Comment by Hedronmx** [comment]
I'll probably give it a go tomorrow :smile:

**Comment by Hedronmx** [comment]
![ying](https://user-images.githubusercontent.com/26935602/58991584-77246580-879d-11e9-9db5-e8d60c5c0f32.png)

![Symbolic Dark](https://user-images.githubusercontent.com/26935602/58992598-1fd3c480-87a0-11e9-83a0-1c830ee2b143.png)

![Symbolic White](https://user-images.githubusercontent.com/26935602/58992608-26623c00-87a0-11e9-88c1-ad74ad7d447d.png)

Something like this?

**Comment by evan-buss** [comment]
Looks good! I really like the main app icon. 

For the wingpanel icons, it would be better if they only use a single color and transparency. It should be more of an outline so that it fits in with the other symbolic icons. 

I had thought that there should be two versions depending on if dark-mode or light-mode is currently enabled, but I don't think the icons will be different enough. So I think a basic yin-yang symbolic logo will do. We would need a version with black lines and a version with white lines to match light and dark wingpanel backgrounds.

Thanks for the contribution!

**Comment by Hedronmx** [comment]
I couln't find any info on how to do symbolic or wingpanel icons... So i kind of winged it...

Ill see what can I do, by just using white or black.

**Comment by evan-buss** [comment]
If you install LookBook from the appcenter it shows the regular and symbolic icons for a bunch of different applications. They are basically just minimal versions of the normal icons.

**Comment by Hedronmx** [comment]
Like this? I did two variants in case you want to use a toggle mechanic.

![Symbolic Dark](https://user-images.githubusercontent.com/26935602/59140312-afb87080-8950-11e9-8953-5f144c7b77ef.png)
![Symbolic Dark 2](https://user-images.githubusercontent.com/26935602/59140313-afb87080-8950-11e9-8897-cfc5aa4513a1.png)
![Symbolic White](https://user-images.githubusercontent.com/26935602/59140314-afb87080-8950-11e9-85d4-c238ec7cc584.png)
![Symbolic White 2](https://user-images.githubusercontent.com/26935602/59140316-b0510700-8950-11e9-9bbb-072b36d8d06d.png)


![Symbolic Dark Variant](https://user-images.githubusercontent.com/26935602/59140349-2f463f80-8951-11e9-88e5-99e27a53349a.png)
![Symbolic White 2 Variant](https://user-images.githubusercontent.com/26935602/59140350-2fded600-8951-11e9-8657-50c56fa3942a.png)

**Comment by evan-buss** [comment]
Those look great! If you can send all the different variants, I can play around with it to see which looks best in the wingpanel. Are they SVG format? If so you could either send the source files of the desktop and wingpanel icons or export them into these sizes.
![image](https://user-images.githubusercontent.com/18509589/59150217-d973a500-89ed-11e9-96df-e3a1cc0b4711.png)

Thanks for the help!

**Comment by Hedronmx** [comment]
Here you go!
Let me know if you need any changes.... Guide is a bit weird.

https://drive.google.com/open?id=1JgGcVjnrM6IA6UN6hrHhZEWCDUgx7zwh
